pub mod acp;
pub mod chat_channel;
pub mod conversations;
mod error;
pub mod experts;
pub mod files;
pub mod folder_commands;
pub mod folders;
pub mod git;
pub mod mcp;
pub mod model_provider;
pub mod project_boot;
pub mod system_settings;
pub mod terminal;
pub mod version_control;
pub mod web_server;
pub mod workspace_state;
